/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
static yyconst short int yy_accept[247] =
    {   0,
        0,    0,   50,   48,   46,   47,   48,   48,   34,   35,
       32,   30,   29,   31,   33,   24,   24,   27,   28,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   36,    0,    0,    0,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,   45,
        0,    0,    0,    0,    0,    0,    0,   24,   24,    0,
       24,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   10,   23,
       23,   23,   23,   23,   23,   23,   23,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   25,   25,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,    3,   23,
       23,   23,   14,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,    0,   39,   43,   44,   42,   41,   40,
       37,    0,   39,   26,   43,   26,   44,   26,   42,   26,
       41,   26,   40,   26,   37,   26,    0,   39,   43,   44,
       42,   41,   40,   37,    0,   25,   23,   23,   23,   23,
       23,   23,   23,   23,   19,   23,   23,   23,    5,   23,
       12,   23,   23,   23,   23,   23,   17,    7,   23,   11,

       23,   23,   23,   22,   38,   38,   26,   38,   23,   23,
       23,   23,   23,   16,   15,   23,   23,   23,   23,   18,
        2,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   13,   23,    6,    8,    1,    4,   23,   23,   23,
        9,   21,   23,   23,   20,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   19,   19,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   19,   19,   19,
        1,    1,    1,    1,    1,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   19,   19,   48,   19,   49,
       50,   19,   19,   51,   52,   53,   54,   19,   19,   19,
       19,   19,   55,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[282] =
    {   0,
        0,    0,  451,   38,   48,  847,   65,   78,   88,   98,
      108,  118,  128,  148,  158,  171,  153,  181,  191,  201,
      211,  221,  220,   32,   35,   47,  123,   54,   73,  164,
       48,   64,   83,  235,  421,  417,   66,   49,  426,  414,
      442,  847,   82,   97,  117,  139,  109,  120,  442,  847,
      157,  223,  234,  241,  251,  138,  177,  432,  192,  202,
      260,    0,  414,  410,  157,  159,  419,  407,   30,  421,
      410,  399,  245,  400,  383,  392,  382,  255,    0,  387,
      399,  260,  374,  374,  387,  367,  363,  356,  388,    0,
        0,    0,    0,    0,    0,    0,  275,  277,  279,  281,

      283,  285,  290,  294,  148,  405,  404,  403,  402,  401,
      400,  399,  389,  287,  847,  289,  379,  304,  359,  414,
      469,  524,  579,  634,  372,  365,  375,  350,  362,  368,
      350,  201,    0,  370,  344,  366,  175,  336,  339,  352,
      339,  333,  341,    0,  847,  847,  847,  847,  847,  847,
      847,  315,  379,  847,  378,  847,  377,  847,  376,  847,
      375,  847,  374,  847,  373,  847,  371,  370,  359,  355,
      354,  353,  352,  351,  310,  312,  689,    0,    0,    0,
        0,    0,    0,    0,    0,  335,  323,  304,    0,  313,
        0,  299,  304,  323,  305,  312,    0,    0,  297,    0,

      321,  293,  298,    0,  847,  336,  847,  336,    0,  318,
      303,  288,  317,    0,    0,  312,  294,  314,  282,    0,
        0,  295,  303,  285,  296,  274,  252,  267,  248,  238,
      228,    0,  220,    0,    0,    0,    0,  201,  203,  195,
        0,    0,  192,  132,    0,  847,  744,  747,   60,  750,
      753,  756,  759,  762,  765,  768,  771,  774,  777,  780,
      783,  786,  789,  792,  795,  798,  801,  804,  807,  810,
      813,  816,  819,  822,  825,  828,  831,  834,  837,  840,
      843
    } ;

static yyconst short int yy_def[282] =
    {   0,
      246,    1,  246,  246,  246,  246,  247,  248,  246,  246,
      246,  246,  246,  246,  246,  246,   14,  246,  246,  249,
      249,  249,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  246,  246,  246,  246,  246,  246,  246,
      247,  246,  247,  247,  247,  247,  247,  247,  248,  246,
      248,  248,  248,  248,  248,  248,  246,  246,  246,  246,
      246,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  246,  250,
      251,  252,  253,  254,  255,  256,  247,  257,  258,  259,

      260,  261,  262,  263,  248,  264,  265,  266,  267,  268,
      269,  270,  246,  246,  246,  246,  249,  271,  272,  273,
      274,  275,  276,  277,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  278,  246,  246,  246,  246,  246,  246,
      246,  279,  247,  246,  247,  246,  247,  246,  247,  246,
      247,  246,  247,  246,  247,  246,  280,  248,  248,  248,
      248,  248,  248,  248,  246,  246,  281,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  246,  247,  246,  248,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,    0,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246
    } ;

static yyconst short int yy_nxt[903] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,    4,   15,   16,   17,   18,   19,   20,   20,   21,
       22,   23,   24,   20,   20,   25,   26,   20,   20,   20,
       27,   20,   28,   20,   29,   20,   20,   30,   20,   31,
       20,   20,   20,   32,   20,   20,   20,   20,   20,   20,
       20,   20,   33,   20,   34,   35,  125,   62,  117,   36,
       62,   37,   62,   78,   38,   35,   39,   40,   42,   36,
       93,   37,   62,   62,   38,   82,   39,   40,   79,   62,
       50,   77,   43,   94,   62,   42,   44,   91,   45,   62,
       86,   46,   92,   47,   48,   51,   80,   62,   62,   52,

       42,   53,   87,   83,   54,   35,   55,   56,   62,   36,
       97,   37,   42,   62,   38,   35,   39,   40,   84,   36,
       42,   37,   62,   42,   38,   35,   39,   40,   98,   36,
      103,   37,   62,   88,   38,   35,   39,   40,   99,   36,
       50,   37,   42,  100,   38,   35,   39,   40,   62,   36,
       50,   37,  104,  245,   38,   81,   39,   40,   57,   50,
      101,   58,   59,  246,   60,   35,   61,   61,  167,   36,
      112,   37,   62,  102,   38,   35,   39,   40,  119,   36,
      121,   37,   60,  120,   38,  105,   39,   40,   35,   62,
      113,  114,   36,  122,   37,  197,   85,   38,   35,   39,

       40,  198,   36,   60,   37,   61,   61,   38,   35,   39,
       40,  244,   36,   62,   37,  115,  116,   38,   63,   39,
       40,  192,   64,  243,   65,   50,  193,   66,   69,   67,
       68,  242,   64,  241,   65,   70,   50,   66,   63,   67,
       68,  240,   64,   50,   65,   62,   71,   66,   73,   67,
       68,   74,   35,   50,  106,  107,   36,  239,   37,  238,
      108,   38,  109,   39,   40,  129,  123,   75,   76,   62,
       72,   60,  111,   61,   61,  110,  123,  137,   42,   41,
      154,   41,  156,   41,  158,   41,  160,   41,  162,  134,
      237,  118,   41,  164,  236,  152,   41,  166,   60,  235,

      175,  175,  176,  176,  145,  145,  234,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,   41,  207,  145,
      145,   60,  233,  175,  175,  176,  176,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,   50,   42,
      204,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,   50,   50,   50,   50,   50,  145,  146,
      146,   50,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,   50,   50,  146,  146,   42,   42,   42,   42,
       42,   42,   42,  204,  203,  202,  201,  200,  199,  196,
      195,  194,  191,  190,  189,  188,  187,  186,  185,  177,

       60,   50,   50,   50,   50,   50,   50,   50,  144,  143,
      142,  141,  140,  146,  147,  147,  139,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  138,  136,  147,
      147,  135,  133,  132,  131,  130,  128,  127,  126,  124,
      123,  118,  117,   60,   50,   42,   96,   95,   90,   89,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  147,  148,
      148,  246,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  246,  246,  148,  148,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  148,  149,  149,  246,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  246,  246,  149,
      149,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  149,  150,
      150,  246,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  246,  246,  150,  150,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  150,  151,  151,  246,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  246,  246,  151,
      151,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  151,  205,
      205,  246,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  246,  246,  205,  205,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  205,   41,   41,   41,   49,   49,   49,
      145,  246,  145,  146,  246,  146,  147,  246,  147,  148,
      246,  148,  149,  246,  149,  150,  246,  150,  151,  246,
      151,  153,  153,  153,  155,  155,  155,  157,  157,  157,
      159,  159,  159,  161,  161,  161,  163,  163,  163,  165,
      165,  165,  168,  168,  168,  169,  169,  169,  170,  170,

      170,  171,  171,  171,  172,  172,  172,  173,  173,  173,
      174,  174,  174,  178,  246,  178,  179,  246,  179,  180,
      246,  180,  181,  246,  181,  182,  246,  182,  183,  246,
      183,  184,  246,  184,  205,  246,  205,  206,  206,  206,
      208,  208,  208,  209,  246,  209,    3,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246
    } ;

static yyconst short int yy_chk[903] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,   69,   24,   69,    4,
       25,    4,  249,   25,    4,    5,    4,    4,    7,    5,
       38,    5,   26,   31,    5,   28,    5,    5,   25,   28,
        8,   24,    7,   38,   25,   43,    7,   37,    7,   32,
       31,    7,   37,    7,    7,    8,   26,   31,   29,    8,

       44,    8,   32,   28,    8,    9,    8,    8,   33,    9,
       43,    9,   47,   32,    9,   10,    9,    9,   29,   10,
       45,   10,   29,   48,   10,   11,   10,   10,   44,   11,
       47,   11,   33,   33,   11,   12,   11,   11,   45,   12,
       56,   12,   46,   45,   12,   13,   12,   12,   27,   13,
      105,   13,   48,  244,   13,   27,   13,   13,   14,   51,
       46,   14,   14,   17,   17,   14,   17,   17,  105,   14,
       56,   14,   27,   46,   14,   15,   14,   14,   65,   15,
       66,   15,   16,   65,   15,   51,   15,   15,   16,   30,
       57,   57,   16,   66,   16,  137,   30,   16,   18,   16,

       16,  137,   18,   59,   18,   59,   59,   18,   19,   18,
       18,  243,   19,   30,   19,   60,   60,   19,   20,   19,
       19,  132,   20,  240,   20,   52,  132,   20,   21,   20,
       20,  239,   21,  238,   21,   21,   53,   21,   22,   21,
       21,  233,   22,   54,   22,   23,   22,   22,   23,   22,
       22,   23,   34,   55,   52,   53,   34,  231,   34,  230,
       53,   34,   54,   34,   34,   73,   73,   23,   23,   23,
       22,   61,   55,   61,   61,   54,   78,   82,   97,   98,
       98,   99,   99,  100,  100,  101,  101,  102,  102,   78,
      229,   82,  103,  103,  228,   97,  104,  104,  114,  227,

      114,  114,  116,  116,  118,  118,  226,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  152,  152,  118,
      118,  175,  225,  175,  175,  176,  176,  224,  223,  222,
      219,  218,  217,  216,  213,  212,  211,  210,  208,  206,
      203,  202,  201,  199,  196,  195,  194,  193,  192,  190,
      188,  187,  186,  174,  173,  172,  171,  170,  118,  119,
      119,  169,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  168,  167,  119,  119,  165,  163,  161,  159,
      157,  155,  153,  143,  142,  141,  140,  139,  138,  136,
      135,  134,  131,  130,  129,  128,  127,  126,  125,  117,

      113,  112,  111,  110,  109,  108,  107,  106,   89,   88,
       87,   86,   85,  119,  120,  120,   84,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,   83,   81,  120,
      120,   80,   77,   76,   75,   74,   72,   71,   70,   68,
       67,   64,   63,   58,   49,   41,   40,   39,   36,   35,
        3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  120,  121,
      121,    0,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,    0,    0,  121,  121,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  121,  122,  122,    0,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,    0,    0,  122,
      122,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  122,  123,
      123,    0,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,    0,    0,  123,  123,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  123,  124,  124,    0,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,    0,    0,  124,
      124,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  124,  177,
      177,    0,  177,  177,  177,  177,  177,  177,  177,  177,

      177,  177,    0,    0,  177,  177,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  177,  247,  247,  247,  248,  248,  248,
      250,    0,  250,  251,    0,  251,  252,    0,  252,  253,
        0,  253,  254,    0,  254,  255,    0,  255,  256,    0,
      256,  257,  257,  257,  258,  258,  258,  259,  259,  259,
      260,  260,  260,  261,  261,  261,  262,  262,  262,  263,
      263,  263,  264,  264,  264,  265,  265,  265,  266,  266,

      266,  267,  267,  267,  268,  268,  268,  269,  269,  269,
      270,  270,  270,  271,    0,  271,  272,    0,  272,  273,
        0,  273,  274,    0,  274,  275,    0,  275,  276,    0,
      276,  277,    0,  277,  278,    0,  278,  279,  279,  279,
      280,  280,  280,  281,    0,  281,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexo.l"
#define INITIAL 0
#line 2 "lexo.l"
#include "bisony.tab.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ts.h" 
#include "quad.h"

extern int nb_line;
extern int col;
extern YYSTYPE yylval;
extern char save_type[20];

extern char buffer[200];


#line 668 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "lexo.l"


#line 822 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 247 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 847 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Program; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Begin;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_End;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Routine;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "lexo.l"
{insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_ENDR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_Integer;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_Real;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_Logical;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Character;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_If; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Then;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_Else;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_Dowhile;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext); return Kw_For;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_EndIf;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_EndDo;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_READ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_WRITE ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_CALL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_EQUIVALENCE ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "lexo.l"
{ insertKw(yytext, "KW"); yylval.strVal = strdup(yytext);return Kw_DIMENSION ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "lexo.l"
return Logical;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "lexo.l"
{
    // Vérifier la longueur de l'identificateur
    if (yyleng > 10) {
        printf("L'identificateur %s dans la ligne %d est trop grand !\n", yytext, nb_line);
    } else {
        // Insérer l'identificateur dans la table des identificateurs
         insertIdfCst(yytext, "idf", save_type, buffer);
        yylval.strVal = strdup(yytext);
        return IDENTIFIER;
    }
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "lexo.l"
{
    yylval.INTEGER = atoi(yytext);
    if (yylval.INTEGER < -32768 || yylval.INTEGER > 32767) {
        printf("Erreur : Valeur entière hors de la plage autorisée dans la ligne %d : %s\n", nb_line, yytext);
    } else {
        return INTEGER;
    }
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "lexo.l"
{
    yylval.Real = atof(yytext);
    if (yylval.Real < -32768.32768 || yylval.Real > 32767.32767) {
        printf("Erreur : Valeur réelle hors de la plage autorisée dans la ligne %d : %s\n", nb_line, yytext);
    } else {
        return Real;
    }
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "lexo.l"
return CHARACTER ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return PV;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 86 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return AFF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return V ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 88 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return ADD ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 89 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return SOUS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return MUL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return DIV;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return PO;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return PF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext);return AO;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return or; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return and; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "lexo.l"
{insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return EQ ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return NE ;} 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return LT ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "lexo.l"
{insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return LE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "lexo.l"
{ insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return GE;} 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "lexo.l"
{insertSepKw(yytext, "Sep"); yylval.strVal = strdup(yytext); return GL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "lexo.l"
/* Commentaire */ 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "lexo.l"

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "lexo.l"
nb_line++;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "lexo.l"
{printf ("erreur lexicale: entite non reconnue a la ligne %d\n",nb_line);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "lexo.l"
ECHO;
	YY_BREAK
#line 1174 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 247 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 247 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 246);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 110 "lexo.l"
